build: false
image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 3.7

install:
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%  # Delete sh.exe from PATH (mingw32-make fix)
  - ps: >-
      switch($env:PYTHON_VERSION) {
          "2.7" {$env:MINICONDA = """C:\Miniconda"""}
          "3.4" {$env:MINICONDA = """C:\Miniconda34"""}
          "3.5" {$env:MINICONDA = """C:\Miniconda35"""}
          "3.6" {$env:MINICONDA = """C:\Miniconda36"""}
          default {$env:MINICONDA = """C:\Miniconda36"""}
      }
  - ps: >-
      if($env:PLATFORM -eq "x64") {
          $env:MINICONDA += "-x64";
          $env:PATH += ";C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin"
      }
      else {$env:PATH += ";C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin"}
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy nose pandas scikit-learn pytest
  - activate test-environment
  - cd python-package
  - pip install rgf_python

test_script:
  - pytest tests/ -v -s
