build: false
image: Visual Studio 2015

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.5
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7

install:
  - ps: >-
      switch($env:PYTHON_VERSION) {
          "2.7" {$env:MINICONDA = """C:\Miniconda"""}
          "3.4" {$env:MINICONDA = """C:\Miniconda34"""}
          "3.5" {$env:MINICONDA = """C:\Miniconda35"""}
          "3.6" {$env:MINICONDA = """C:\Miniconda36"""}
          default {$env:MINICONDA = """C:\Miniconda36"""}
      }
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=%PYTHON_VERSION% scikit-learn
  - activate test-environment
  - set SKLEARN_SITE_JOBLIB=true
  - pip install rgf_python joblib

test_script:
  - python test.py
